### ISSUE TITLE
Input of train algorithms becomes none

### ISSUE THREAD

**Issue by ambroiseb** [Ikomia-dev/IkomiaStudio#29]
**Describe the bug**
Input of type "deep learning dataset" becomes "none". After that, nothing can be plugged to the input slot.

**To Reproduce**
1. Pick any train algorithm from the hub et connect it to root (without dataset plugin before)
2. Run
3. See exception because input dataset is not plugged to a dataset (normal behaviour)
4. Close the link between root and train algorithm
5. See the bug

**Environment:**
 - OS: ubuntu 20.04
 - Ikomia Studio version 0.10.0

**Comment by LudoBar** [comment]
Missing CDatasetIO registration in I/O factory. Fixed in Ikomia-dev/IkomiaCore@53e745e069544ef6ca2b5e82b1c9a78c7164d237
